### ISSUE TITLE
I get this error when trying to login with the old account 

### ISSUE THREAD

**Issue by ghost** [natanlao/reddit-transfer#2]
Traceback (most recent call last):
  File "/home/violet/reddit-transfer/reddit_transfer.py", line 178, in <module>
    main(sys.argv[1:])
  File "/home/violet/reddit-transfer/reddit_transfer.py", line 170, in main
    Config(args.username).login()
  File "/home/violet/reddit-transfer/reddit_transfer.py", line 61, in login
    self.config[username] = {
NameError: name 'username' is not defined

I get this after entering my client id and secret

**Comment by natanlao** [comment]
Hi! Thanks for reporting this. This was a bug I introduced that should now be fixed in 9ac8b740ab3bf1d0fce3bc6c3107c430ad020634. Let me know if the new version works for you.

**Comment by ghost** [comment]
So i tried it again, there wasn't the initial bug that i had posted but this came up after it subscribed to a bunch of subreddits,
```
INFO:reddit-transfer:Subscribe to /r/OutOfTheLoop
INFO:reddit-transfer:Subscribe to /r/VioletEvergarden
INFO:reddit-transfer:Subscribe to /r/u_AutoLovepon
INFO:reddit-transfer:Subscribe to /r/FumetsuNoAnataE
INFO:reddit-transfer:Subscribe to /r/MXLinux
INFO:reddit-transfer:Subscribe to /r/u_totestsuswopfi
Traceback (most recent call last):
  File "/home/violet/reddit-transfer/reddit_transfer.py", line 179, in <module>
    main(sys.argv[1:])
  File "/home/violet/reddit-transfer/reddit_transfer.py", line 173, in main
    sync_data(args.src_user, args.dst_user)
  File "/home/violet/reddit-transfer/reddit_transfer.py", line 120, in sync_data
    dst.reddit.subreddit(sub).subscribe()
  File "/home/violet/.local/lib/python3.9/site-packages/praw/models/reddit/subreddit.py", line 1402, in subscribe
    self._reddit.post(API_PATH["subscribe"], data=data)
  File "/home/violet/.local/lib/python3.9/site-packages/praw/reddit.py", line 752, in post
    return self._objectify_request(
  File "/home/violet/.local/lib/python3.9/site-packages/praw/reddit.py", line 666, in _objectify_request
    self.request(
  File "/home/violet/.local/lib/python3.9/site-packages/praw/reddit.py", line 848, in request
    return self._core.request(
  File "/home/violet/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 324, in request
    return self._request_with_retries(
  File "/home/violet/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 260, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.Forbidden: received 403 HTTP response
```

My old account was suspended, so it could that have been the reason or is it the programs fault?

**Comment by natanlao** [comment]
> My old account was suspended, so it could that have been the reason or is it the programs fault?

Inferring that your old account is `/u/totestsuswopfi`, my first guess is that the error occurs because you can't subscribe to a suspended subreddit/account. Try unsubscribing from the source account (maybe via https://reddit.com/reddits) and running again.

**Comment by ghost** [comment]
> > My old account was suspended, so it could that have been the reason or is it the programs fault?
> 
> Inferring that your old account is `/u/totestsuswopfi`, my first guess is that the error occurs because you can't subscribe to a suspended subreddit/account. Try unsubscribing from the source account (maybe via https://reddit.com/reddits) and running again.

It worked now thanks!
